name: PR Quality Checker

on:
  pull_ request_target:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hi"
