name: PR Quality Checker

on:
  pull_request_target:
permissions:
  contents: read
  pull-requests: write

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      # Check out PR code
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # Run quality check
      - shell: bash
        env:
          FLAG: ${{ secrets.FLAG }}
        run: ./safetychecker.sh
