name: PR Quality Checker

on:
  pull_request_target:
permissions:
  contents: read
  pull-requests: write

jobs:
  check-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        env:
          FLAG: ${{ secrets.FLAG }}
        run: ./safetychecker.sh
